// This code was autogenerated.

using Common.Models;
using System.Linq;

namespace Game.Rendering
{
    public static class TextureResources
    {
        public static Font @LatoItalic(this Resources resources) => resources.Fonts.Single(item => item.FontData.Info.Face == "LatoItalic");
        public static Font @LatoRegular(this Resources resources) => resources.Fonts.Single(item => item.FontData.Info.Face == "LatoRegular");

        public static AtlasTexture @Box(this Resources resources) => resources.Textures.Single(item => item.Name == "Box");
        public static AtlasTexture @Default(this Resources resources) => resources.Textures.Single(item => item.Name == "Default");
        public static AtlasTexture @Floor(this Resources resources) => resources.Textures.Single(item => item.Name == "Floor");
        public static AtlasTexture @Grid(this Resources resources) => resources.Textures.Single(item => item.Name == "Grid");
        public static AtlasTexture @LineBlur(this Resources resources) => resources.Textures.Single(item => item.Name == "LineBlur");
        public static AtlasTexture @Wall(this Resources resources) => resources.Textures.Single(item => item.Name == "Wall");
        public static AtlasTexture @WallFade(this Resources resources) => resources.Textures.Single(item => item.Name == "WallFade");

    }
}