// This code was autogenerated.

using Common.Models;
using System.Linq;

namespace Game.Models
{
    public static class ModelResources
    {
        public static ModelFile @Box(this Resources resources) => resources.Models.Single(item => item.Name == "Box");
        public static ModelFile @Exit(this Resources resources) => resources.Models.Single(item => item.Name == "Exit");
        public static ModelFile @ExitMarker(this Resources resources) => resources.Models.Single(item => item.Name == "ExitMarker");
        public static ModelFile @FloorTile(this Resources resources) => resources.Models.Single(item => item.Name == "FloorTile");
        public static ModelFile @Wall(this Resources resources) => resources.Models.Single(item => item.Name == "Wall");

    }
}